apiVersion: v1
kind: ServiceAccount
metadata:
  name: dagster
  namespace: kolkhis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dagster
  namespace: kolkhis
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["create", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dagster
  namespace: kolkhis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dagster
subjects:
  - kind: ServiceAccount
    name: dagster
    namespace: kolkhis
