apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-instance
  namespace: kolkhis
data:
  dagster.yaml: |
    storage:
      postgres:
        postgres_url:
          env: DAGSTER_PG_URL

    run_launcher:
      module: dagster_k8s
      class: K8sRunLauncher
      config:
        service_account_name: dagster
        job_namespace: kolkhis
        load_incluster_config: true
        job_image:
          env: DAGSTER_IMAGE
        env_secrets:
          - dagster-credentials
