apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projects-pvc
  namespace: kolkhis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
