apiVersion: v1
kind: PersistentVolume
metadata:
  name: projects-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/projects
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
