apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolkhis-shell
  namespace: kolkhis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kolkhis-shell
  template:
    metadata:
      labels:
        app: kolkhis-shell
    spec:
      initContainers:
        - name: fix-ssh-owner
          image: busybox:1.37
          command: ["sh", "-c"]
          args:
            - |
              cp /secret/authorized_keys /ssh/authorized_keys
              chown 1000:1000 /ssh/authorized_keys
              chmod 600 /ssh/authorized_keys
          volumeMounts:
            - name: ssh-keys
              mountPath: /secret
              readOnly: true
            - name: ssh-dir
              mountPath: /ssh
      containers:
        - name: shell
          image: ghcr.io/euxinedata/kolkhis-shell:latest
          ports:
            - containerPort: 22
          volumeMounts:
            - name: projects
              mountPath: /home/shelluser/projects
            - name: ssh-dir
              mountPath: /home/shelluser/.ssh
      volumes:
        - name: projects
          persistentVolumeClaim:
            claimName: projects-pvc
        - name: ssh-keys
          secret:
            secretName: shell-ssh-keys
        - name: ssh-dir
          emptyDir: {}
